package bbus

import (
	"testing"
	"fmt"
)

//func Test_DecodePolyline(t *testing.T) {
//	t.Log(DecodePolyline(`.=slbNLBexDjPA;|.=6iTOLBEcjjPA;|-=slbNLBexDjPAPAAAEAAAvWBAbaAAQBEA5+AAT6DAawAA2wBA1VAAMCBAzMAAS7BA2XAAMBAAPAAAwcCAmfAA1UBAGRAAZAAAGAAA3lAAuEAAypAANFAAxKBAUJAA1nAA9EAAPAAACAAA9ZBA7WAAeHBANSAALtCAWiAAvIAAvBAAZtBAsVAAZAAAFAAA9\/AAPIAAPAAACAAAlWAAqAAgNYAAqAAgAAAAAAAAqJAAjRAAyAAAbBAAbNAASvAAgAAAvBAAWGAAYrAAncAAlDDACDAAxUAASAAA5BAAuJAAs\/CAPLAAudDAGAAA1BAABQCAeFAgAAAALAAgYBAACAAgKvAA8AAgb5BAYCAgsdBA1BAgu3BAWCAgCAAAAAAAg2EAWMAgXTCA3FAgvPBALDAgXHDA7HAgAAAAAAAAyVAAfJAAqAAASAAAcNAAbSEAZCAAzwAALAAgAAAABAAAWAAAFGAAOFCA2AAAvSAAvIAAv\/CAuBAAmlAAEAAA1AAAMNAAKhCAJEAAoyAAGmAAOVAAnWAAYAAAZWAA0UAgHUAAsSAgPiAA0fAgKwAAwsAgpTAAFhAgj4AANfBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;`))
//}

//func Test_CodeToGeo(t *testing.T) {
//	t1 := time.Now()
//	p, _ := JDecodePolyline(`.=slbNLBexDjPA;|.=6iTOLBEcjjPA;|-=slbNLBexDjPAPAAAEAAAvWBAbaAAQBEA5+AAT6DAawAA2wBA1VAAMCBAzMAAS7BA2XAAMBAAPAAAwcCAmfAA1UBAGRAAZAAAGAAA3lAAuEAAypAANFAAxKBAUJAA1nAA9EAAPAAACAAA9ZBA7WAAeHBANSAALtCAWiAAvIAAvBAAZtBAsVAAZAAAFAAA9\/AAPIAAPAAACAAAlWAAqAAgNYAAqAAgAAAAAAAAqJAAjRAAyAAAbBAAbNAASvAAgAAAvBAAWGAAYrAAncAAlDDACDAAxUAASAAA5BAAuJAAs\/CAPLAAudDAGAAA1BAABQCAeFAgAAAALAAgYBAACAAgKvAA8AAgb5BAYCAgsdBA1BAgu3BAWCAgCAAAAAAAg2EAWMAgXTCA3FAgvPBALDAgXHDA7HAgAAAAAAAAyVAAfJAAqAAASAAAcNAAbSEAZCAAzwAALAAgAAAABAAAWAAAFGAAOFCA2AAAvSAAvIAAv\/CAuBAAmlAAEAAA1AAAMNAAKhCAJEAAoyAAGmAAOVAAnWAAYAAAZWAA0UAgHUAAsSAgPiAA0fAgKwAAwsAgpTAAFhAgj4AANfBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;`)
//	fmt.Printf("x = %.6f, y = %.6f\n",  p.Ua.Kl.Lat, p.Ua.Kl.Lng)
//	t2 := time.Now()
//	fmt.Printf("Cost time %v\n",t2.Sub(t1))
//	a,_ := DecodePolyline(`.=slbNLBexDjPA;|.=6iTOLBEcjjPA;|-=slbNLBexDjPAPAAAEAAAvWBAbaAAQBEA5+AAT6DAawAA2wBA1VAAMCBAzMAAS7BA2XAAMBAAPAAAwcCAmfAA1UBAGRAAZAAAGAAA3lAAuEAAypAANFAAxKBAUJAA1nAA9EAAPAAACAAA9ZBA7WAAeHBANSAALtCAWiAAvIAAvBAAZtBAsVAAZAAAFAAA9/AAPIAAPAAACAAAlWAAqAAgNYAAqAAgAAAAAAAAqJAAjRAAyAAAbBAAbNAASvAAgAAAvBAAWGAAYrAAncAAlDDACDAAxUAASAAA5BAAuJAAs/CAPLAAudDAGAAA1BAABQCAeFAgAAAALAAgYBAACAAgKvAA8AAgb5BAYCAgsdBA1BAgu3BAWCAgCAAAAAAAg2EAWMAgXTCA3FAgvPBALDAgXHDA7HAgAAAAAAAAyVAAfJAAqAAASAAAcNAAbSEAZCAAzwAALAAgAAAABAAAWAAAFGAAOFCA2AAAvSAAvIAAv/CAuBAAmlAAEAAA1AAAMNAAKhCAJEAAoyAAGmAAOVAAnWAAYAAAZWAA0UAgHUAAsSAgPiAA0fAgKwAAwsAgpTAAFhAgj4AANfBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;`)
//	fmt.Printf("x = %.6f, y = %.6f\n",  a.Points[0].Lat, a.Points[0].Lng)
//	t3 := time.Now()
//	fmt.Printf("Cost time %v\n",t3.Sub(t2))
//	t.Log("Good")
//}

func Test_SeachBusLine(t *testing.T){
	b, e := BusStopSeachBusLine("何贤医院")
	fmt.Println(b.Content[0].Blinfo[0], e)
	t.Log("Good")
}